"""
Spacepod Game Library
Do not edit this file! Instead, look at spacepod_escape.py.
"""

import tsapp
import random

_w = tsapp.GraphicsWindow()
_bg = tsapp.Sprite("Console.png", 0, 0)
_w.add_object(_bg)

_bulbs = []
for i in range(3):
    bulb = tsapp.Sprite("BulbUnlit.png", 625, 87 + 168 * i)
    _bulbs.append(bulb)
    _w.add_object(bulb)

_labels = []
for i in range(3):
    label = tsapp.TextLabel("CourierPrime-Bold.ttf", 180, 68 + 181 * i, 320, 200, "?", tsapp.BLACK)
    _labels.append(label)
    _w.add_object(label)

_correct_answer = str(random.randint(1, 5)) + str(random.randint(1, 5)) + str(random.randint(1, 5))

def get_correct_count(guess):
    right = 0
    for i in range(3):
        if guess[i] == _correct_answer[i]:
            right += 1
    return right

def get_misplaced_count(guess):
    moved = 0
    answer_pool = list(_correct_answer)
    for i in range(3):
        if guess[i] in answer_pool:
            moved += 1
            answer_pool.remove(guess[i])

    return moved - get_correct_count(guess)

def get_answer():
    return _correct_answer
    return ""

def show_screen():
    _w.finish_frame()

def update_screen(guess):
    for i in range(3):
        _labels[i].text = guess[i]

    right_digits = get_correct_count(guess)
    moved_digits = get_misplaced_count(guess)
    for i in range(3):
        if right_digits > i:
            _bulbs[i].image = "BulbGreen.png"
        elif right_digits + moved_digits > i:
            _bulbs[i].image = "BulbYellow.png"
        else:
            _bulbs[i].image = "BulbUnlit.png"

    _w.finish_frame()

def is_guess_valid(guess):
    if len(guess) != 3:
        return False
    for char in guess:
        if not char.isdigit():
            return False
        if int(char) < 1:
            return False
        if int(char) > 5:
            return False
    return True

def show_win():
    emoji = tsapp.Sprite("ResponseHappy.png", 700, 50)
    emoji.flip_x = True
    _w.add_object(emoji)
    _w.finish_frame()


def show_loss():
    emoji = tsapp.Sprite("ResponseUnhappy.png", 700, 50)
    emoji.flip_x = True
    _w.add_object(emoji)
    _w.finish_frame()